name: Build Gradle project (Iris plugin)

on:
  push:

jobs:
  build-gradle-project:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout project sources
      uses: actions/checkout@v2
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 17
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    - name: Run setup with mc 1.18+
      run: ./gradlew setup
    - name: Run bulid Iris plugin
      run: ./gradlew iris
    - name: Release Iris
      if: github.event_name != 'pull_request'
      uses: marvinpinto/action-automatic-releases@master
      with:
        title: "Iris build"
        automatic_release_tag: "build"
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        files: "./Iris-*.jar"   
        prerelease: false
